# Makefile generated by Make My File: https://github.com/MathysCogne/Make_My_File-42

# 📄 Documentation:
# This Makefile is generated automatically by the Make My File program.
# It facilitates the compilation of C programs.
#
# Variables:
# - NAME: Name of the executable or library to create.
# - SRCDIR: Directory where source files are located.
# - OBJDIR: Directory where object files will be stored.
# - INCDIR: Directory containing header files.
# - SRC: List of source files to compile.
# - OBJ: List of object files generated from the source files.
# - CC: The compiler to use (default is 'cc').
# - CFLAGS: Compilation flags (default includes warnings and debugging).
# - LDFLAGS: Linker flags (if any).
# - LIBS: Libraries to link against.
#
# Rules:
# - 'make': Builds the project.
# - 'make clean': Removes object files.
# - 'make fclean': Removes all generated files including the executable.
# - 'make re': Cleans and rebuilds the project.
# - 'make bonus': Builds and includes bonus source files if they exist.
# - 'make regen': Regenerates the Makefile 
#
# Note: Use 'VERBOSE=1' for detailed output during compilation.
#
# Please report any bugs or suggestions at: https://github.com/MathysCogne/Make_My_File-42/issues

NAME = libft.a

SRCDIR = src
OBJDIR = obj
INCDIR = include

# Source Files
SRC = ft_printf/ft_putlunbr_base.c ft_printf/ft_putladdr_base.c ft_printf/ft_putlnbr.c ft_printf/ft_putlstr.c ft_printf/ft_printf.c ft_printf/ft_utils.c libft/ft_strlen.c libft/ft_toupper.c libft/ft_tolower.c libft/ft_strrchr.c libft/ft_lstmap.c libft/ft_strncmp.c libft/ft_strchr.c libft/ft_split.c libft/ft_putchar_fd.c libft/ft_strlcpy.c libft/ft_strmapi.c libft/ft_lstiter.c libft/ft_substr.c libft/ft_atoi.c libft/ft_lstlast.c libft/ft_lstnew.c libft/ft_putnbr_fd.c libft/ft_strjoin.c libft/ft_strdup.c libft/ft_isprint.c libft/ft_memchr.c libft/ft_lstadd_front.c libft/ft_isascii.c libft/ft_isdigit.c libft/ft_lstdelone.c libft/ft_memset.c libft/ft_memcpy.c libft/ft_memcmp.c libft/ft_strtrim.c libft/ft_isalpha.c libft/ft_putstr_fd.c libft/ft_putendl_fd.c libft/ft_isalnum.c libft/ft_strlcat.c libft/ft_lstclear.c libft/ft_bzero.c libft/ft_striteri.c libft/ft_memmove.c libft/ft_itoa.c libft/ft_lstsize.c libft/ft_calloc.c libft/ft_lstadd_back.c libft/ft_strnstr.c get_next_line/get_next_line_utils.c get_next_line/get_next_line.c 
OBJ = $(SRC:.c=.o)

SRC := $(addprefix $(SRCDIR)/, $(SRC))
OBJ := $(patsubst $(SRCDIR)/%, $(OBJDIR)/%, $(OBJ))

# Compiler and Flags
CC = cc
CFLAGS = -Wall -Wextra -Werror -I$(INCDIR) -g3

# Linker Flags and Libraries
LDFLAGS = 
LIBS = 

# Colors
RED     := "\033[1;31m"
GREEN   := "\033[1;32m"
RESET   := "\033[0m"

# Compilation mode (silent by default, set VERBOSE=1 to show commands)
VERBOSE ?= 0
ifeq ($(VERBOSE),1)
  V := 
else
  V := @
endif

# All Rule
all: $(OBJDIR) $(NAME)

# Object Directory Rule
$(OBJDIR):
	$(V)mkdir -p $(OBJDIR) || true

# Dependency Files
DEPDIR = $(OBJDIR)/deps
DEP = $(OBJ:.o=.d)

$(DEPDIR):
	$(V)mkdir -p $(DEPDIR) || true

$(OBJDIR)/%.o: $(SRCDIR)/%.c
	@mkdir -p $(dir $@)
	$(V)$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

-include $(DEP)

# Compilation Rules
$(OBJDIR)/%.o: $(SRCDIR)/%.c | $(OBJDIR) $(DEPDIR)
	$(V)$(CC) $(CFLAGS) -MMD -c $< -o $@
# Linking Rule
$(NAME): $(OBJ)
	$(V)$(AR) rcs $@ $^
	$(V)echo $(GREEN)"🤖 [$(NAME)] Library created ✅"$(RESET)

# Clean Rules
clean:
	$(V)echo $(RED)"🗑️  CLEANING OBJS"$(RESET)
	$(V)rm -rf $(OBJDIR)
	$(V)rm -rf $(DEPDIR)

fclean: clean
	$(V)echo $(RED)"🔥 CLEANING ALL"$(RESET)
	$(V)rm -f $(NAME)

re: fclean all

# Makefile Reconfiguration 
regen:
	makemyfile

.PHONY: all clean fclean re bonus regen
.DEFAULT_GOAL := all
